---
- name: Flatten VM definitions
  set_fact:
    vm_list: "{{ vm_list | default([]) + item.value | dict2items }}"
  loop: "{{ clusters | dict2items }}"

- name: Build VM objects
  set_fact:
    expanded_vms: "{{ expanded_vms | default([]) + [
      {
        'name': item.key,
        'role': item.value.role,
        'cpu': item.value.cpu,
        'memory': item.value.memory,
        'ip': item.value.ip_start
      }
    ] }}"
  loop: "{{ vm_list }}"
