---
- name: Create VM Folders
  community.vmware.vcenter_folder:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: false

    datacenter: "{{ vcenter_datacenter }}"
    folder_name: "{{ item }}"
    folder_type: vm
    state: present
  loop:
    - Kubernetes
    - Infrastructure
    - Controllers
    - Workers
