---
- name: Install Java
  apt:
    name: openjdk-17-jre
    state: present

- name: Create nexus user
  user:
    name: nexus
    system: yes

- name: Download Nexus
  get_url:
    url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
    dest: /opt/nexus.tar.gz

- name: Extract Nexus
  unarchive:
    src: /opt/nexus.tar.gz
    dest: /opt/
    remote_src: yes
