---
- name: Install admin tools
  apt:
    name:
      - awscli
      - kubectl
      - jq
      - htop
    state: present

- name: Add kubectl completion
  shell: |
    echo 'source <(kubectl completion bash)' >> /home/ubuntu/.bashrc
