---
# Environment
environment: dev
project_name: aws-k8s-platform

# AWS
aws_region: us-east-1

# SSH
ansible_user: ubuntu
ansible_ssh_private_key_file: ~/.ssh/my-aws-key.pem
ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

# Kubernetes
kubernetes_version: "1.32"

# Domain Settings
base_domain: lab.local

# Tags
common_tags:
  Environment: dev
  Project: aws-k8s-platform
  ManagedBy: ansible

# AMI
ubuntu_ami: ami-0c7217cdde317cfec

# Storage Defaults
default_volume_type: gp3
default_volume_size: 50

# Networking
vpc_cidr: 10.0.0.0/16

public_subnet_cidr: 10.0.1.0/24
private_subnet_cidr: 10.0.2.0/24

availability_zone: us-east-1a

# Kubernetes Networking
pod_network_cidr: 10.244.0.0/16
service_network_cidr: 10.96.0.0/12

# DNS
cluster_dns_ip: 10.96.0.10

# NTP
ntp_servers:
  - 0.amazon.pool.ntp.org
  - 1.amazon.pool.ntp.org
