---
- name: Create Subnets
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Public subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ public_subnet_cidr }}"
        region: "{{ aws_region }}"
        az: "{{ availability_zones[0] }}"
      register: public_subnet

    - name: Private subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ private_subnet_cidr }}"
        region: "{{ aws_region }}"
        az: "{{ availability_zones[0] }}"
      register: private_subnet
