---
- name: Create Internet Gateway
  hosts: localhost
  gather_facts: false

  tasks:

    - name: IGW
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ aws_region }}"
      register: igw
