---
- name: Security Groups
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Kubernetes SG
      amazon.aws.ec2_security_group:
        name: k8s-sg
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ aws_region }}"
        rules:
          - proto: tcp
            ports:
              - 22
              - 6443
              - 10250
            cidr_ip: 10.0.0.0/16
