---
- name: Validate AWS Dynamic Inventory
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../vars/aws.yml

  tasks:

    - name: Show discovered EC2 instances
      amazon.aws.ec2_instance_info:
        region: "{{ aws_region }}"
        filters:
          "tag:Project": "{{ project_name }}"
          "tag:Environment": "{{ environment }}"
      register: aws_instances

    - name: Print instance summary
      debug:
        msg: >
          Name={{ item.tags.Name }}
          Role={{ item.tags.Role }}
          IP={{ item.private_ip_address }}
      loop: "{{ aws_instances.instances }}"
